### PR TITLE
Fix the solidus executable and make it rely on just Thor

### LINKED ISSUE #47: Allow users to easily update the extension to new standards
Mimic what's done by `rails app:update` and let users run a command that will add missing files and ask what to do for existing ones (with diff/skip/…, Thor already supports this).

Related: #46

### PR DESCRIPTION
**Pull request by elia**
Fixes #47

## Summary

- Only use Thor (instead of mixing with optparse) and let it print the help message
- Define a base SolidusCLI command that will be the base for `extension`
- Define an `extension` command with a generate subcommand, which is also the default
- Cleanup the implementation and make it work with both relative and absolute paths
- add `bin/solidus` and `bin/rake` for easy development and less typing

## Checklist

- [x] I have structured the commits for clarity and conciseness.
- [x] I have added relevant automated tests for this change.
- [x] I have added an entry to the changelog for this change.

### CODE REVIEW

File: lib/solidus_dev_support/solidus_cli.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
+# frozen_string_literal: true
+
+require 'thor'
+require 'solidus_dev_support/extension'
+
+class SolidusDevSupport::SolidusCLI < Thor
```
Comment (aldesantis) [inline lib/solidus_dev_support/solidus_cli.rb]: Couple of things:

1. Is there a reason for using `class SolidusDevSupport::SolidusCLI` instead of nesting `class SolidusCLI` within a `module SolidusDevSupport` definition?
2. `SoliudsCLI` is not compatible with Zeitwerk, which would expect it to be defined at `solidus_c_l_i.rb`. How about renaming it to `SolidusCli`? It's a no-brainer and prevents any potential problems.

Comment (elia) [reply lib/solidus_dev_support/solidus_cli.rb]: I do that by default because it keeps everything on a single level of indentation and avoids some constant lookup situations. But I'll expand it and rename the class to SolidusCommand. 

---

In the future I think it's something that should be extracted (to `solidus-cli`?) and added as a dependency of the `solidus` gem, but that's another story.

**Comment by aldesantis** [comment]
@elia please add changelog entries for the bugfix and enhancements before merging.
